name: checks
on: [push, pull_request]
jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run services
        run: docker-compose up --build -d
      - name: Run tests
        run: docker-compose exec -T booker pipenv run test
