name: checks
on: [push, pull_request]
jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose -f docker/docker-compose-dev-test.yml --env-file .env.example up -V --remove-orphans --exit-code-from backend --build
